package com.InvoicifyPro.InvoicifyPro.enums.expense;

public enum ExpenseType {
    PUBLICITE_FACEBOOK,
    PUBLICITE_INSTAGRAM,
    PUBLICITE_TIKTOK,
    COUT_PRODUITS,
    FRAIS_TRANSACTION_KLARNA,
    FRAIS_TRANSACTION_STRIPE,
    FRAIS_TRANSACTION_CHECKIFY,
    FRAIS_ANNULATION,
    SERVICE,
    LIVRAISON

}
